# Generated by Django 5.0.7 on 2024-07-22 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('name', models.CharField(max_length=255, verbose_name='Project name')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_project', to=settings.AUTH_USER_MODEL, verbose_name='Author of the project')),
                ('contributor', models.ManyToManyField(related_name='contributor_project', to=settings.AUTH_USER_MODEL, verbose_name='Contributors of the project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('name', models.CharField(max_length=255, verbose_name='Task name')),
                ('condition', models.CharField(choices=[('To do', 'Todo'), ('In progress', 'In Progress'), ('Done', 'Done'), ('Hot fix', 'Hot Fix')], default='To do', verbose_name='Task condition')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_task', to=settings.AUTH_USER_MODEL, verbose_name='Author of the task')),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributor_task', to=settings.AUTH_USER_MODEL, verbose_name='Contributor of task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_task', to='projects.project', verbose_name='Task of project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
